//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Agent {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Agent() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestCTI.App_Resources.Agent", typeof(Agent).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent.
        /// </summary>
        public static string Agente {
            get {
                return ResourceManager.GetString("Agente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call.
        /// </summary>
        public static string Call {
            get {
                return ResourceManager.GetString("Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An user has been added to the conference..
        /// </summary>
        public static string CallConferenced {
            get {
                return ResourceManager.GetString("CallConferenced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The call has been diverted..
        /// </summary>
        public static string CallDiverted {
            get {
                return ResourceManager.GetString("CallDiverted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call ended!.
        /// </summary>
        public static string CallEnded {
            get {
                return ResourceManager.GetString("CallEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call failed!.
        /// </summary>
        public static string CallFailed {
            get {
                return ResourceManager.GetString("CallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The call has been put on hold..
        /// </summary>
        public static string CallOnHold {
            get {
                return ResourceManager.GetString("CallOnHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The call has been retrieved..
        /// </summary>
        public static string CallRetrieved {
            get {
                return ResourceManager.GetString("CallRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The call data could not be saved..
        /// </summary>
        public static string CallSavedFail {
            get {
                return ResourceManager.GetString("CallSavedFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call stored successfully..
        /// </summary>
        public static string CallSavedOK {
            get {
                return ResourceManager.GetString("CallSavedOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call transferred successfully..
        /// </summary>
        public static string CallTransferred {
            get {
                return ResourceManager.GetString("CallTransferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confer....
        /// </summary>
        public static string Confer {
            get {
                return ResourceManager.GetString("Confer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Conf....
        /// </summary>
        public static string EndConf {
            get {
                return ResourceManager.GetString("EndConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dispositions for this campaign could not be obtained..
        /// </summary>
        public static string ErrorDispositions {
            get {
                return ResourceManager.GetString("ErrorDispositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Pause Code could not be saved. Try it later..
        /// </summary>
        public static string ErrorSavePauseCode {
            get {
                return ResourceManager.GetString("ErrorSavePauseCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The campaign script could not be obtained..
        /// </summary>
        public static string ErrorScript {
            get {
                return ResourceManager.GetString("ErrorScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hang Up.
        /// </summary>
        public static string HangUp {
            get {
                return ResourceManager.GetString("HangUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold.
        /// </summary>
        public static string Hold {
            get {
                return ResourceManager.GetString("Hold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold Calls.
        /// </summary>
        public static string HoldCalls {
            get {
                return ResourceManager.GetString("HoldCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert a phone number.
        /// </summary>
        public static string InsertPhone {
            get {
                return ResourceManager.GetString("InsertPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call.
        /// </summary>
        public static string Llamada {
            get {
                return ResourceManager.GetString("Llamada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calllogs.
        /// </summary>
        public static string Menu_Calllog {
            get {
                return ResourceManager.GetString("Menu_Calllog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calls.
        /// </summary>
        public static string Menu_Calls {
            get {
                return ResourceManager.GetString("Menu_Calls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Menu_Contacts {
            get {
                return ResourceManager.GetString("Menu_Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no active call!.
        /// </summary>
        public static string NoActiveCall {
            get {
                return ResourceManager.GetString("NoActiveCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to recognize the device associated with the active agent..
        /// </summary>
        public static string NoActiveDevice {
            get {
                return ResourceManager.GetString("NoActiveDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user does not have pause codes available..
        /// </summary>
        public static string NoPasusesAvailable {
            get {
                return ResourceManager.GetString("NoPasusesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was not possible to obtain the PauseCodes of this user..
        /// </summary>
        public static string NotPausesUser {
            get {
                return ResourceManager.GetString("NotPausesUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The call can not be retrieved because there is an active call..
        /// </summary>
        public static string NotRetrieve {
            get {
                return ResourceManager.GetString("NotRetrieve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user&apos;s campaigns could not be obtained..
        /// </summary>
        public static string ObtCampUserError {
            get {
                return ResourceManager.GetString("ObtCampUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time in pause has ended. It will be automatically logged out..
        /// </summary>
        public static string PauseTimeOutLoggout {
            get {
                return ResourceManager.GetString("PauseTimeOutLoggout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time in pause has ended. You will be &quot;Ready&quot; automatically..
        /// </summary>
        public static string PauseTimeOutReady {
            get {
                return ResourceManager.GetString("PauseTimeOutReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve.
        /// </summary>
        public static string Retrieve {
            get {
                return ResourceManager.GetString("Retrieve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a campaign....
        /// </summary>
        public static string SelectCampaign {
            get {
                return ResourceManager.GetString("SelectCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Call Disposition....
        /// </summary>
        public static string SelectDisposition {
            get {
                return ResourceManager.GetString("SelectDisposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a call on hold!.
        /// </summary>
        public static string SelectHoldCall {
            get {
                return ResourceManager.GetString("SelectHoldCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Pause Code....
        /// </summary>
        public static string SelectPauseCode {
            get {
                return ResourceManager.GetString("SelectPauseCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a valid Pause Code..
        /// </summary>
        public static string SelectValidPauseC {
            get {
                return ResourceManager.GetString("SelectValidPauseC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string Transfer {
            get {
                return ResourceManager.GetString("Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is not associated with any campaign..
        /// </summary>
        public static string UserNotCampaign {
            get {
                return ResourceManager.GetString("UserNotCampaign", resourceCulture);
            }
        }
    }
}
