//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Login {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Login() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestCTI.App_Resources.Login", typeof(Login).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must authenticate with a device..
        /// </summary>
        public static string AuthDevice {
            get {
                return ResourceManager.GetString("AuthDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling....
        /// </summary>
        public static string Calling {
            get {
                return ResourceManager.GetString("Calling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not initialize this device:.
        /// </summary>
        public static string CanNotInitialize {
            get {
                return ResourceManager.GetString("CanNotInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to change to Ready status..
        /// </summary>
        public static string ChangeToReadyFail {
            get {
                return ResourceManager.GetString("ChangeToReadyFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change to Ready state successfully completed..
        /// </summary>
        public static string ChangeToReadyOk {
            get {
                return ResourceManager.GetString("ChangeToReadyOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string Desea {
            get {
                return ResourceManager.GetString("Desea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a username..
        /// </summary>
        public static string EnterUsername {
            get {
                return ResourceManager.GetString("EnterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error logging the supervisor..
        /// </summary>
        public static string ErrorLogSuper {
            get {
                return ResourceManager.GetString("ErrorLogSuper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to obtain user data.
        /// </summary>
        public static string ErrorObtUserData {
            get {
                return ResourceManager.GetString("ErrorObtUserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In a call!.
        /// </summary>
        public static string InCall {
            get {
                return ResourceManager.GetString("InCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming call!.
        /// </summary>
        public static string IncomingCall {
            get {
                return ResourceManager.GetString("IncomingCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External incoming call!.
        /// </summary>
        public static string InExternalCall {
            get {
                return ResourceManager.GetString("InExternalCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are logged in with a different device:.
        /// </summary>
        public static string LoggedOtherDevice {
            get {
                return ResourceManager.GetString("LoggedOtherDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_btn {
            get {
                return ResourceManager.GetString("Login_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Your Information.
        /// </summary>
        public static string Login_header {
            get {
                return ResourceManager.GetString("Login_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your Roll....
        /// </summary>
        public static string Login_Roll {
            get {
                return ResourceManager.GetString("Login_Roll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station.
        /// </summary>
        public static string Login_Station {
            get {
                return ResourceManager.GetString("Login_Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string Login_user {
            get {
                return ResourceManager.GetString("Login_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The User field is required.
        /// </summary>
        public static string Login_ValidAgent {
            get {
                return ResourceManager.GetString("Login_ValidAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Password field is required.
        /// </summary>
        public static string Login_ValidPass {
            get {
                return ResourceManager.GetString("Login_ValidPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should choose your Roll.
        /// </summary>
        public static string Login_ValidRoll {
            get {
                return ResourceManager.GetString("Login_ValidRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Station field is required.
        /// </summary>
        public static string Login_ValidStation {
            get {
                return ResourceManager.GetString("Login_ValidStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press No if you want to continue work. Press Yes to logout current user..
        /// </summary>
        public static string LogoutMessage {
            get {
                return ResourceManager.GetString("LogoutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to log out?.
        /// </summary>
        public static string LogoutTitle {
            get {
                return ResourceManager.GetString("LogoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not make this call..
        /// </summary>
        public static string MakeCallFail {
            get {
                return ResourceManager.GetString("MakeCallFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not connect to the core..
        /// </summary>
        public static string NotConnectCore {
            get {
                return ResourceManager.GetString("NotConnectCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device ID (source or destination) not specified..
        /// </summary>
        public static string NotDevice {
            get {
                return ResourceManager.GetString("NotDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not phone specify.
        /// </summary>
        public static string NotphoneError {
            get {
                return ResourceManager.GetString("NotphoneError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caller ID (ucid) not specified..
        /// </summary>
        public static string NotUcid {
            get {
                return ResourceManager.GetString("NotUcid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Extension.
        /// </summary>
        public static string PhoneExtension {
            get {
                return ResourceManager.GetString("PhoneExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , Please login.
        /// </summary>
        public static string PlesaseLogin {
            get {
                return ResourceManager.GetString("PlesaseLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt is being made to log in a user without a device Id..
        /// </summary>
        public static string RequireDevice {
            get {
                return ResourceManager.GetString("RequireDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Password field is required..
        /// </summary>
        public static string RequirePassword {
            get {
                return ResourceManager.GetString("RequirePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Username field is required..
        /// </summary>
        public static string RequireUsername {
            get {
                return ResourceManager.GetString("RequireUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out.
        /// </summary>
        public static string Salir {
            get {
                return ResourceManager.GetString("Salir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent.
        /// </summary>
        public static string SelectVal1 {
            get {
                return ResourceManager.GetString("SelectVal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local User.
        /// </summary>
        public static string SelectVal2 {
            get {
                return ResourceManager.GetString("SelectVal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown username..
        /// </summary>
        public static string UnknownUsername {
            get {
                return ResourceManager.GetString("UnknownUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
