//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Supervisor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Supervisor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestCTI.App_Resources.Supervisor", typeof(Supervisor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calls on hold.
        /// </summary>
        public static string CallsOnHold {
            get {
                return ResourceManager.GetString("CallsOnHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected agents.
        /// </summary>
        public static string ConnectedAgents {
            get {
                return ResourceManager.GetString("ConnectedAgents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device should not be empty..
        /// </summary>
        public static string DeviceEmpty {
            get {
                return ResourceManager.GetString("DeviceEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading phone partial..
        /// </summary>
        public static string ErrorLoadPhonePartial {
            get {
                return ResourceManager.GetString("ErrorLoadPhonePartial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading list of queue calls..
        /// </summary>
        public static string ErrorLoadQueueCall {
            get {
                return ResourceManager.GetString("ErrorLoadQueueCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In a call.
        /// </summary>
        public static string InCall {
            get {
                return ResourceManager.GetString("InCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen.
        /// </summary>
        public static string Listen {
            get {
                return ResourceManager.GetString("Listen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login phone extension.
        /// </summary>
        public static string LoginPhone {
            get {
                return ResourceManager.GetString("LoginPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connected agents..
        /// </summary>
        public static string NoAgentsConnected {
            get {
                return ResourceManager.GetString("NoAgentsConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No queued calls..
        /// </summary>
        public static string NoQueuedCalls {
            get {
                return ResourceManager.GetString("NoQueuedCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device has not been initialized. Reasons:.
        /// </summary>
        public static string NotDeviceInitialized {
            get {
                return ResourceManager.GetString("NotDeviceInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To perform this action you must log in with a device..
        /// </summary>
        public static string NotDeviceLog {
            get {
                return ResourceManager.GetString("NotDeviceLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued calls.
        /// </summary>
        public static string QueuedCalls {
            get {
                return ResourceManager.GetString("QueuedCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the action that you wish to realize on the agent..
        /// </summary>
        public static string SelectAction {
            get {
                return ResourceManager.GetString("SelectAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait time.
        /// </summary>
        public static string WaitTime {
            get {
                return ResourceManager.GetString("WaitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whisper.
        /// </summary>
        public static string Whisper {
            get {
                return ResourceManager.GetString("Whisper", resourceCulture);
            }
        }
    }
}
