//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestCTI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignPauseCodes
    {
        public int Id { get; set; }
        public int IdCampaign { get; set; }
        public int IdPauseCode { get; set; }
        public int MaxDuration { get; set; }
        public int MaxDailyEvents { get; set; }
        public bool AutoReady { get; set; }
        public bool Active { get; set; }
    
        public virtual Campaign Campaign { get; set; }
        public virtual PauseCodes PauseCodes { get; set; }
    }
}
