//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestCTI.Models
{
    using System;
    
    public partial class ct_GetPauseCodes
    {
        public int Id { get; set; }
        public int Value { get; set; }
        public string Name { get; set; }
        public int MaxDuration { get; set; }
        public int MaxDailyEvents { get; set; }
        public bool AutoReady { get; set; }
    }
}
