//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestCTI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBCTIEntities : DbContext
    {
        public DBCTIEntities()
            : base("name=DBCTIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Switch> Switch { get; set; }
        public virtual DbSet<UserLocation> UserLocation { get; set; }
        public virtual DbSet<UserSkill> UserSkill { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Campaign> Campaign { get; set; }
        public virtual DbSet<CampaignSkills> CampaignSkills { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<Skills> Skills { get; set; }
        public virtual DbSet<VDN> VDN { get; set; }
        public virtual DbSet<CampaignType> CampaignType { get; set; }
        public virtual DbSet<PauseCodes> PauseCodes { get; set; }
        public virtual DbSet<CampaignPauseCodes> CampaignPauseCodes { get; set; }
        public virtual DbSet<Calls> Calls { get; set; }
        public virtual DbSet<DispositionCampaigns> DispositionCampaigns { get; set; }
        public virtual DbSet<Dispositions> Dispositions { get; set; }
    
        public virtual ObjectResult<ct_GetPauseCodes> GetPauseCodes(string agent_name)
        {
            var agent_nameParameter = agent_name != null ?
                new ObjectParameter("agent_name", agent_name) :
                new ObjectParameter("agent_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ct_GetPauseCodes>("GetPauseCodes", agent_nameParameter);
        }
    }
}
