//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestCTI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPauseCodes
    {
        public int Id { get; set; }
        public int IdUser { get; set; }
        public int IdPauseCode { get; set; }
        public int QuantDailyEvents { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual PauseCodes PauseCodes { get; set; }
        public virtual Users Users { get; set; }
    }
}
